server:
  port: 8081

spring:
  application:
    name: transaction-service
  kafka:
    bootstrap-servers: localhost:29092

app:
  topic:
    transactions: transactions

logging:
  level:
    com.securebank: INFO
    org.apache.kafka: WARN
